### ISSUE TITLE
Adding Mulch

### ISSUE THREAD

**Issue by gjf** [neoblackxt/AnyWebView#11] opened 2023-07-19 21:09 UTC
As [future development of Bromite is unclear](https://github.com/bromite/bromite/issues/2610), it would be nice to add [Mulch](https://gitlab.com/divested-mobile/mulch) support in this module.

Currently it is possible [only using patch from recovery or using Magisk module](https://github.com/A4Alpha/mulch-webview-overlay).

I love AnyWebview concept and would like stay on it, but it should add some current WebView variants,

**Comment by neoblackxt** [comment] 2023-07-20 02:15
duplicate of #8

**Closed by neoblackxt** 2023-07-20 02:15 UTC
Labels: duplicate
