### ISSUE TITLE
Does this work with the mulch webview?

### ISSUE THREAD

**Issue by Venderbad** [neoblackxt/AnyWebView#7] opened 2023-03-28 06:18 UTC
I tried to install the mulch webview apk from divestOS fdroid repo and attempted to get it working with this module, but somehow it did not show up in the selectable webview implementation list even if the mulch webview apk is installed for all users. Any clue?

Android 13, LineageOS 20, OnePlus 8, Rooted with Magisk, LSPosed framework.

Thanks for all the work so far by the way 🧡, the module is amazing, and it has enabled me to use bromite webview for several months.😁

**Comment by neoblackxt** [comment] 2023-05-03 04:47
Closed for duplicate of https://github.com/neoblackxt/AnyWebView/issues/8

**Closed by neoblackxt** 2023-05-03 04:47 UTC
Labels: duplicate, enhancement
